# Generated by Django 5.0.3 on 2024-03-11 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_d_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Task',
        ),
    ]
