# Generated by Django 5.0.3 on 2024-03-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("t_d_list", "0002_rename_todo_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_datetime"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="t_d_list.tag"),
        ),
    ]
